<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>csp</string>
    </array>
    <key>name</key>
    <string>CSPM</string>
    <key>patterns</key>
    <array>
<!--         <dict>
            <key>match</key>
            <string>\\\<\\\></string>
            <key>name</key>
            <string>constant.language.empty-list.cspm</string>
        </dict> -->
<!--         <dict>
            <key>match</key>
            <string>\b[A-Z]\w*\b</string>
            <key>name</key>
            <string>constant.other.cspm</string>
        </dict>
 -->
        <dict>
            <key>include</key>
            <string>#comments</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[(FD|T|F)=</string>
            <key>name</key>
            <string>keyword.other.semanticmodel.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>-&gt;|\[\]|\|~\||\|\|\||\[\||\|]|\[\[|\]\]|\|\||;|/\\</string>
            <key>name</key>
            <string>keyword.operator.process.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>{\||\|}|{|}|\.\.|:|#|&lt;-|&lt;-&gt;|==|&lt;|&gt;|&lt;=|&gt;=|@|&amp;</string>
            <key>name</key>
            <string>keyword.operator.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(assert|datatype|let|within|newtype|channel|external|transparent)\b</string>
            <key>name</key>
            <string>keyword.other.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(if|then|else)\b</string>
            <key>name</key>
            <string>keyword.control.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b([0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(true|false|True|False)\b</string>
            <key>name</key>
            <string>support.constant.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <!-- Generate using:
                ghci CSPM/Prelude.hs
                head (map stringName allBuiltins)++concat (map (\b -> '|':stringName b) allBuiltins)
            -->
            <string>\b(length|length|null|head|tail|concat|elem|union|inter|diff|Union|Inter|member|card|empty|set|Set|Seq|seq|Int|Bool|Proc|Events|true|false|True|False|STOP|SKIP|CHAOS|prioritise|productions|extensions|diamond|normal|sbisim|tau_loop_factor|model_compress|explicate|wbisim|chase)\b</string>
            <key>name</key>
            <string>support.function.prelude.cspm</string>
        </dict>
        <dict>
            <key>match</key>
            <string>,</string>
            <key>name</key>
            <string>punctuation.separator.comma.cspm</string>
        </dict>
        <dict>
            <!-- |\([|!%$+\-.,=&lt;/&gt;]+\) -->
            <key>match</key> 
            <string>^\s*([a-zA-Z0-9_']+)\s*(\(.*?\)|)\s*=</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cspm</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.function.cspm</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>block_comment</key>
        <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>\{-</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.cspm</string>
                </dict>
            </dict>
            <key>end</key>
            <string>-\}</string>
            <key>name</key>
            <string>comment.block.cspm</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#block_comment</string>
                </dict>
            </array>
        </dict>
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.cspm</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(--).*$\n?</string>
                    <key>name</key>
                    <string>comment.line.double-dash.cspm</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#block_comment</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.cspm</string>
    <key>uuid</key>
    <string>0B927AA7-ED5F-285B-082833EB60238D17</string>
</dict>
</plist>
